kind: pipeline
name: Packaging

steps:
- name: Debian/Ubuntu source packages
  pull: always
  image: ivaradi/debian-build:groovy
  commands:
    - /build/run.sh scripts/build debian-sourcepackages.sh
  environment:
    DEBIAN_SECRET_KEY:
      from_secret: DEBIAN_SECRET_KEY
    DEBIAN_SECRET_IV:
      from_secret: DEBIAN_SECRET_IV
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
