kind: pipeline
name: Debian

steps:
- name: build
  image: ivaradi/jsprog-debian-build:latest
  commands:
    - env
    - pwd
    - ls -al
    - git fetch origin debian/dist/groovy/${DRONE_TARGET_BRANCH}
    - git checkout debian/dist/groovy/${DRONE_TARGET_BRANCH}
    - git merge ${DRONE_COMMIT}
    - debuild -S
  environment:
    DEBIAN_SECRET_KEY:
      from_secret: DEBIAN_SECRET_KEY
    DEBIAN_SECRET_IV:
      from_secret: DEBIAN_SECRET_IV
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
