kind: pipeline
name: Native build

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:kinetic
  commands:
    - /build/run.sh scripts/build native.sh kinetic
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Bionic binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:bionic
  commands:
    - /build/run.sh scripts/build debian-binary.sh bionic
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Focal binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:focal
  commands:
    - /build/run.sh scripts/build debian-binary.sh focal
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Jammy binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:jammy
  commands:
    - /build/run.sh scripts/build debian-binary.sh jammy
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Kinetic binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:kinetic
  commands:
    - /build/run.sh scripts/build debian-binary.sh kinetic
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Buster binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:buster
  commands:
    - /build/run.sh scripts/build debian-binary.sh buster
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Bullseye binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:bullseye
  commands:
    - /build/run.sh scripts/build debian-binary.sh bullseye
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Source Packages

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:jammy
  commands:
    - /build/run.sh scripts/build debian-sourcepackages.sh
  environment:
    DEBIAN_SECRET_KEY:
      from_secret: DEBIAN_SECRET_KEY
    DEBIAN_SECRET_IV:
      from_secret: DEBIAN_SECRET_IV
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
depends_on:
- Native build
- Bionic binary package
- Focal binary package
- Jammy binary package
- Kinetic binary package
- Buster binary package
- Bullseye binary package
