kind: pipeline
name: Native build

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:groovy
  commands:
    - /build/run.sh scripts/build native.sh groovy
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Bionic binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:bionic
  commands:
    - /build/run.sh scripts/build debian-binary.sh bionic
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Focal binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:focal
  commands:
    - /build/run.sh scripts/build debian-binary.sh focal
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Hirsute binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:hirsute
  commands:
    - /build/run.sh scripts/build debian-binary.sh hirsute
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Impish binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:impish
  commands:
    - echo "Due to problems with Docker and the Impish image,"
    - echo "this build is not run currently."
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Buster binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:buster
  commands:
    - /build/run.sh scripts/build debian-binary.sh buster
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Bullseye binary package

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:bullseye
  commands:
    - /build/run.sh scripts/build debian-binary.sh bullseye
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: Source Packages

steps:
- name: build
  pull: always
  image: ivaradi/debian-build:impish
  commands:
    - /build/run.sh scripts/build debian-sourcepackages.sh
  environment:
    DEBIAN_SECRET_KEY:
      from_secret: DEBIAN_SECRET_KEY
    DEBIAN_SECRET_IV:
      from_secret: DEBIAN_SECRET_IV
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
depends_on:
- Native build
- Bionic binary package
- Focal binary package
- Hirsute binary package
- Impish binary package
- Buster binary package
- Bullseye binary package
